language: php
php:
  - 7.4
  - 7.3
  - 7.2
services:
  - mysql
os: linux
notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+.*$/"

cache:
  - composer
  - "$HOME/.composer/cache"

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - PANTHEON_WPVULNDB_API_TOKEN=NI7BJgWm40MppXU3MedPTqsc9O3W6urSkClOcacagzM
    - secure: qVuABE9laRLFk+2J5pJjmJI6YmRqEEailCvkwiN0Gqx+68KaB2t64djEnVYxWo2nxzZE7jZ0cNabQxd1mvFOWAZAvCetlKmLBfO8qoBsfMtqimWprSUA3fXqqXJ9YDmscK/zeOzM0cbnD7HbJ+bB7Zl6zHcjzTD019PD8FT3iDc=

before_script:
  - bash bin/install-package-tests.sh
  - composer install

script: "./vendor/bin/behat --ansi"

before_deploy:
  - bash bin/prepare.sh

deploy:
  provider: releases
  token:
    secure: mF9U4mO+B+lJKqK6rqom/nOlsLHDRlBVgVIQxUuO4xCPuygD1eer8Hfkvqo58tpsPWF24Iqek4NyFTZ7dY78vmhVUPCxS/nq/+6A0Dyg3uqFYK5F+Sn60e46ZATSOJVDlKTr62ZR04dq0tjrFBwXfNXqv9RMQGjaOVD/U+tKTsw=
  file: wp_launch_check.phar
  on:
    repo: pantheon-systems/wp_launch_check
    tags: true
